version: '3.8'

services:

  calendar-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    environment:
      DATABASE_SERVER: ${DATABASE_SERVER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3002:3002'
    volumes:
      - ./src:/app/src

  calendar-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d